/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import conexao.ConexaoBD;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author Saulc
 */
public class Tela_Prontuario extends javax.swing.JFrame {
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public void limpar (){
        txtNome.setText (null);
        txtDataNascimento.setText (null);
        txtCPF.setText (null);
        txtSUS.setText (null);
        txtIdade.setText (null);
        txtData.setText (null);
        cbMaculino.setSelected(false);
        cbFeminino.setSelected(false);
        txtEndereco.setText (null);
        txtNumero.setText(null);
        txtBairro.setText(null);
        txtUF.setText(null);
        txtCidade.setText(null);
        txtCEP.setText(null);
    }
    public Tela_Prontuario() {
        initComponents();
        conexao = ConexaoBD.conector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVoltar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        txtDataNascimento = new javax.swing.JTextField();
        txtData = new javax.swing.JTextField();
        txtCEP = new javax.swing.JTextField();
        txtCPF = new javax.swing.JTextField();
        txtSUS = new javax.swing.JTextField();
        txtIdade = new javax.swing.JTextField();
        txtCor = new javax.swing.JTextField();
        cbMaculino = new javax.swing.JCheckBox();
        cbFeminino = new javax.swing.JCheckBox();
        txtNome = new javax.swing.JTextField();
        txtUF = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVoltar.setText("VOLTAR");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 390, -1, -1));

        btnSalvar.setText("PROXIMO");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        btnLimpar.setText("LIMPAR");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        btnAtualizar.setText("ATUALIZAR");
        getContentPane().add(btnAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        txtDataNascimento.setBackground(new java.awt.Color(0, 153, 0));
        txtDataNascimento.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtDataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 260, 30));

        txtData.setBackground(new java.awt.Color(0, 153, 0));
        txtData.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtData, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, 160, 30));

        txtCEP.setBackground(new java.awt.Color(0, 153, 0));
        txtCEP.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtCEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 250, 30));

        txtCPF.setBackground(new java.awt.Color(0, 153, 0));
        txtCPF.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 190, 30));

        txtSUS.setBackground(new java.awt.Color(0, 153, 0));
        txtSUS.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtSUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 190, 30));

        txtIdade.setBackground(new java.awt.Color(0, 153, 0));
        txtIdade.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 210, 30));

        txtCor.setBackground(new java.awt.Color(0, 153, 0));
        txtCor.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 210, 30));

        cbMaculino.setText("Masculino");
        cbMaculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMaculinoActionPerformed(evt);
            }
        });
        getContentPane().add(cbMaculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        cbFeminino.setText("Feminino");
        cbFeminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFemininoActionPerformed(evt);
            }
        });
        getContentPane().add(cbFeminino, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        txtNome.setBackground(new java.awt.Color(0, 153, 0));
        txtNome.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 330, 30));

        txtUF.setBackground(new java.awt.Color(0, 153, 0));
        txtUF.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtUF, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 260, 60, 30));

        txtCidade.setBackground(new java.awt.Color(0, 153, 0));
        txtCidade.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 340, 30));

        txtEndereco.setBackground(new java.awt.Color(0, 153, 0));
        txtEndereco.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 310, 30));

        txtNumero.setBackground(new java.awt.Color(0, 153, 0));
        txtNumero.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 90, 30));

        txtBairro.setBackground(new java.awt.Color(0, 153, 0));
        txtBairro.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, 120, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/TELA 7.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
     Tela_Paciente paciente = new Tela_Paciente();
        paciente.setVisible (true);
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
    Tela_Prontuario_2 prontuarios = new Tela_Prontuario_2();
        prontuarios.setVisible (true);
        dispose();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
    limpar();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void cbMaculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMaculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMaculinoActionPerformed

    private void cbFemininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFemininoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFemininoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Prontuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Prontuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Prontuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Prontuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Prontuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JCheckBox cbFeminino;
    private javax.swing.JCheckBox cbMaculino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCEP;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCor;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtDataNascimento;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtSUS;
    private javax.swing.JTextField txtUF;
    // End of variables declaration//GEN-END:variables
}
