/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import conexao.ConexaoBD;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author Saulc
 */
public class Tela_Prontuario_2 extends javax.swing.JFrame {
    
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public void limpar (){
        txtDescriçãodeSintomas.setText (null);
        txtPressaoArterial.setText (null);
        txtReceitaMedica.setText (null);
        txtTemperatura.setText (null);
        cbGrave.setSelected(false);
        cbLeve.setSelected(false);
        cbModerado.setSelected(false);        
    }
    
    public Tela_Prontuario_2() {
        initComponents();
        conexao = ConexaoBD.conector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVoltar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        cbGrave = new javax.swing.JCheckBox();
        cbLeve = new javax.swing.JCheckBox();
        cbModerado = new javax.swing.JCheckBox();
        txtReceitaMedica = new javax.swing.JTextField();
        txtTemperatura = new javax.swing.JTextField();
        txtPressaoArterial = new javax.swing.JTextField();
        txtDescriçãodeSintomas = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVoltar.setText("VOLTAR");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 390, -1, -1));

        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        btnLimpar.setText("LIMPAR");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        btnAtualizar.setText("ATUALIZAR");
        getContentPane().add(btnAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        cbGrave.setText("GRAVE");
        getContentPane().add(cbGrave, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        cbLeve.setText("LEVE");
        getContentPane().add(cbLeve, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        cbModerado.setText("MODERADO");
        getContentPane().add(cbModerado, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        txtReceitaMedica.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(txtReceitaMedica, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 630, 100));

        txtTemperatura.setBackground(new java.awt.Color(0, 153, 0));
        txtTemperatura.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtTemperatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 140, 30));

        txtPressaoArterial.setBackground(new java.awt.Color(0, 153, 0));
        txtPressaoArterial.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtPressaoArterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 260, 30));

        txtDescriçãodeSintomas.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(txtDescriçãodeSintomas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 630, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/TELA 8.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
     Tela_Prontuario prontuario = new Tela_Prontuario();
        prontuario.setVisible (true);
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Prontuario_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Prontuario_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Prontuario_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Prontuario_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Prontuario_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JCheckBox cbGrave;
    private javax.swing.JCheckBox cbLeve;
    private javax.swing.JCheckBox cbModerado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtDescriçãodeSintomas;
    private javax.swing.JTextField txtPressaoArterial;
    private javax.swing.JTextField txtReceitaMedica;
    private javax.swing.JTextField txtTemperatura;
    // End of variables declaration//GEN-END:variables
}
