/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import conexao.ConexaoBD;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author Saulc
 */
public class Tela_Login extends javax.swing.JFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    
    public void login(){
        String sql = "SELECT * FROM tbfuncionario WHERE Nome=? AND Senha=?";
        try{
            pst= conexao. prepareStatement(sql);
            pst.setString (1, txtUsuario.getText());
             pst.setString (2, txtSenha.getText());
             rs= pst.executeQuery();
             if(rs.next()){
                 Tela_Principal principal = new Tela_Principal();
                 principal.setVisible(true);
                 dispose();
   
        }else{
               JOptionPane.showMessageDialog(null,"Usuário ou Senha Incorreto!","Erro", JOptionPane.ERROR_MESSAGE);
             }
                 } catch (Exception e) {
             JOptionPane.showMessageDialog(null,e);
        }
    }
    
    public Tela_Login() {
        initComponents();
        conexao=ConexaoBD.conector();
        
        
         if (conexao != null){
           lblStatusdeConexao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/BDAtivo.png")));
         
       }else{
           lblStatusdeConexao.setIcon(new javax.swing.ImageIcon(getClass().getResource("imagens/BDInativo.png")));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsuario = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        lblStatusdeConexao = new javax.swing.JLabel();
        ckbMostarSenha = new javax.swing.JCheckBox();
        txtSenha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsuario.setBackground(new java.awt.Color(0, 153, 0));
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 210, 30));

        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 70, -1));

        btnCadastrar.setText("CADASTARAR");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, -1, -1));
        getContentPane().add(lblStatusdeConexao, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 70, 70));

        ckbMostarSenha.setBackground(new java.awt.Color(255, 255, 255));
        ckbMostarSenha.setForeground(new java.awt.Color(0, 153, 0));
        ckbMostarSenha.setText("Mostar Senha");
        ckbMostarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbMostarSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(ckbMostarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        txtSenha.setBackground(new java.awt.Color(0, 153, 0));
        txtSenha.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 210, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/TELA 1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
    Tela_Cadastro_Funcionario cadastro = new Tela_Cadastro_Funcionario();
       cadastro.setVisible (true);
       dispose();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void ckbMostarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbMostarSenhaActionPerformed
     if(ckbMostarSenha.isSelected()){
            txtSenha.setEchoChar((char)0);
            ckbMostarSenha.setText("Ocultar Senha");
        }else{
            txtSenha.setEchoChar('*');
            ckbMostarSenha.setText("Mostrar Senha");
        }
    }//GEN-LAST:event_ckbMostarSenhaActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
             
                if(txtUsuario.getText().equals("")
     
               || txtSenha.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Todos os Campos são Obrigatórios!");
     
           }else{
                login();    
           }
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnLogin;
    private javax.swing.JCheckBox ckbMostarSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblStatusdeConexao;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
